### ISSUE TITLE
CI 툴을 젠킨스 말고 travis-ci는 어떤가요?

### ISSUE THREAD

**Issue by woniper** [NoPainNoCode/meow#3]
https://github.com/marketplace/travis-ci
이건데 어떻게 사용하는지 잘 모르겠는데요. 이번에 이걸 사용해보는건 어떨까요??

**Comment by HanShin** [comment]
@woniper 어떤 장점이 있어서 추천하는 것인지? 아니면 학습목적으로?
travis-ci 쓰는건 문제가 없을 것 같긴함. 
적용하는건 내가 담당해보고싶음(물론 학습은 다 같이)

**Comment by 01B** [comment]
@woniper jenkins는 완전 무료지? 비교해보고 사용하자

**Comment by woniper** [comment]
@HanShin 
장점은 사실 잘 모르겠고 젠킨스는 우리가 직접 서버에 설치해서 사용해야되는데 travis-ci는 그게 필요없어 보여서요. open source는 무료이기도하고, 많이 사용하는거 같아요. 물론 학습 용도가 제일 크긴하죠.
그럼 형이 적용해주세요. 저도 시간나는대로 학습은 할게요.

**Comment by woniper** [comment]
@01B 
네 젠킨스도 무료긴한데, 이것도 open source는 무료라서 써보는것도 좋을거 같아서요. 비교는 그럼 형이 해주실래요? @HanShin 형이 적용해주시고

**Comment by 01B** [comment]
@woniper @HanShin 오늘내로 비교해보고 자정전에 공유해줄께요~

**Comment by woniper** [comment]
@01B 위키에 부탁드려요

**Comment by 01B** [comment]
@woniper 네~

**Comment by woniper** [comment]
(travis-ci document)[https://blog.outsider.ne.kr/782]

**Comment by woniper** [comment]
travis-ci 쓰기로 결정
